name: ci-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: cache .jbang folder
        uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
          restore-keys: ${{ runner.os }}-jbang-

      - name: compile scripts
        uses: jbangdev/jbang-action@v0.84.2
        with:
          script: Catalog.java
        env:
          JBANG_REPO: /root/.jbang/repository
          GITHUB_TOKEN: ${{ secrets.ISSUE_GITHUB_TOKEN }}
